name: Trigger auto deployment for container-app-sc223wh6z3zgq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-sc223wh6z3zgq-AutoDeployTrigger-0fecd90d-7ef0-49fd-ba9e-6927fe2cf25c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPSC223WH6Z3ZGQ_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPSC223WH6Z3ZGQ_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPSC223WH6Z3ZGQ_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPSC223WH6Z3ZGQ_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPSC223WH6Z3ZGQ_REGISTRY_PASSWORD }}
          containerAppName: container-app-sc223wh6z3zgq
          resourceGroup: expresssample8581a437
          imageToBuild: default/container-app-sc223wh6z3zgq:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


